/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeaderboardEntry = IDL.Record({
  'teamName' : IDL.Text,
  'rank' : IDL.Nat,
  'playerName' : IDL.Text,
  'totalPoints' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const EntryFeeType = IDL.Variant({
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'entryFeeType' : EntryFeeType,
  'dateTime' : IDL.Text,
  'prizePool' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'registerPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeaderboardEntry = IDL.Record({
    'teamName' : IDL.Text,
    'rank' : IDL.Nat,
    'playerName' : IDL.Text,
    'totalPoints' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  const EntryFeeType = IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'entryFeeType' : EntryFeeType,
    'dateTime' : IDL.Text,
    'prizePool' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'registerPlayer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };