/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : DepositStatus,
  'user' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'amount' : IDL.Float64,
  'screenshot' : ExternalBlob,
  'utr_number' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'freefireUid' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'teamName' : IDL.Text,
  'rank' : IDL.Nat,
  'playerName' : IDL.Text,
  'totalPoints' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const RoomJoinStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const RoomType = IDL.Variant({
  'duo' : IDL.Null,
  'solo' : IDL.Null,
  'clashSquad' : IDL.Null,
  'squad' : IDL.Null,
  'fullMap' : IDL.Null,
});
export const Room = IDL.Record({
  'startTime' : IDL.Int,
  'name' : IDL.Text,
  'joinedSlots' : IDL.Nat,
  'totalSlots' : IDL.Nat,
  'joinStatus' : RoomJoinStatus,
  'entryFee' : IDL.Text,
  'roomType' : RoomType,
  'prizePool' : IDL.Text,
});
export const EntryFeeType = IDL.Variant({
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'entryFeeType' : EntryFeeType,
  'entryFee' : IDL.Text,
  'dateTime' : IDL.Text,
  'prizePool' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const RegisterUserResult = IDL.Variant({
  'emailExists' : IDL.Null,
  'success' : IDL.Null,
});
export const SubmitDepositResult = IDL.Variant({
  'utrDuplicate' : IDL.Null,
  'success' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveTransaction' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deposit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getAllPendingTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTransactionRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'registerPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RegisterUserResult],
      [],
    ),
  'rejectTransaction' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitDeposit' : IDL.Func(
      [IDL.Float64, IDL.Text, ExternalBlob],
      [SubmitDepositResult],
      [],
    ),
  'withdraw' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : DepositStatus,
    'user' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'amount' : IDL.Float64,
    'screenshot' : ExternalBlob,
    'utr_number' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'freefireUid' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'teamName' : IDL.Text,
    'rank' : IDL.Nat,
    'playerName' : IDL.Text,
    'totalPoints' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  const RoomJoinStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const RoomType = IDL.Variant({
    'duo' : IDL.Null,
    'solo' : IDL.Null,
    'clashSquad' : IDL.Null,
    'squad' : IDL.Null,
    'fullMap' : IDL.Null,
  });
  const Room = IDL.Record({
    'startTime' : IDL.Int,
    'name' : IDL.Text,
    'joinedSlots' : IDL.Nat,
    'totalSlots' : IDL.Nat,
    'joinStatus' : RoomJoinStatus,
    'entryFee' : IDL.Text,
    'roomType' : RoomType,
    'prizePool' : IDL.Text,
  });
  const EntryFeeType = IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'entryFeeType' : EntryFeeType,
    'entryFee' : IDL.Text,
    'dateTime' : IDL.Text,
    'prizePool' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const RegisterUserResult = IDL.Variant({
    'emailExists' : IDL.Null,
    'success' : IDL.Null,
  });
  const SubmitDepositResult = IDL.Variant({
    'utrDuplicate' : IDL.Null,
    'success' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveTransaction' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deposit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getAllPendingTransactions' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTransactionRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'registerPlayer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [RegisterUserResult],
        [],
      ),
    'rejectTransaction' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitDeposit' : IDL.Func(
        [IDL.Float64, IDL.Text, ExternalBlob],
        [SubmitDepositResult],
        [],
      ),
    'withdraw' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };